development:
  dialect: postgres
  database: weight_development
  user: atiuser
  password: atipassword
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://atiuser:atipassword@127.0.0.1:5432/weight_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://atiuser:atipassword@127.0.0.1:5432/weight"}}